### ISSUE TITLE
Upgrade database from Beta3 to v3

### ISSUE THREAD

**Issue by MohammadKani** [IdentityServer/Thinktecture.IdentityServer3.EntityFramework#39]
hi

i working around with IdSrv3 [Beta] + IdSrv-EF [Beta] for a while and now in the new release v3 i see the database is changed. since i already have a db with data, how can i upgrade my exists database to compatible latest version?

**Comment by brockallen** [comment]
We don't have any upgrade script. The expectation is that you use migrations in your use of the EF library to manage data migration across versions.

**Comment by MohammadKani** [comment]
thanks for quick reply.
