### ISSUE TITLE
Where is the Consent table?

### ISSUE THREAD

**Issue by MohammadKani** [IdentityServer/Thinktecture.IdentityServer3.EntityFramework#40]
when i run this application,. it's create all tables (clinet, scopes, ...) but for Consent & Token there is no table ! where dose this project store consents? i think it's not in memory because it's work fine even after restart the app.

**Comment by brockallen** [comment]
There are 3 different features (Scopes, Client, and Operational):
https://identityserver.github.io/Documentation/docs/ef/overview.html
You need to opt into each one.

**Comment by MohammadKani** [comment]
i know, but just like default example in source code, i use this code :
(factory.RegisterOperationalServices(efConfig);

and it's look like the EF handle the consent or token values, but there is no Consent or Token table created in my db.
the project work correctly but i can not find out how

**Comment by brockallen** [comment]
Oh I suspect you haven't done anything in IdSvr to yet create the tables (like consent, or code flow).

**Comment by MohammadKani** [comment]
as the matter of the fact, i do ! 
and that's amaze me, how does it work even after restart the IdSvr, because if i misconfig anything, at least it should not remeber my Consent to test client, but id dose.
so just let be clear, if i all the things goes right and use IdSvr, there should be a Toke and Consent table in database?

**Comment by MohammadKani** [comment]
i think there is a little bug, i just got the latest version and everything goes alright

thank you

**Comment by bureus** [comment]
I have the same issue, i receive both ID, Access and Refresh tokens using scope offline_access and the authorization code flow. I do have entries in the consent table but nothing in the Tokens table..

**Comment by dotnetrules** [comment]
@MohammadKani I'm having the exact same issue as you did.  I'm glad to hear you resolved it.  Can I please ask from which branch did you grab the latest updates from which resolved this for you?

Also I'm interested as to how you manage and add new Clients, Scopes etc? Can you share what IdentityServer3.Admin project(s) you are using to achieve this?

Thanks :+1:
